[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd apps/task-engine && npm ci"]

[phases.build]
cmds = ["cd apps/task-engine && npm run build"]

[start]
cmd = "cd apps/task-engine && node .next/standalone/server.js"
